### ISSUE TITLE
FileNotFoundError when running modules

### ISSUE THREAD

**Issue by maroskukan** [ansible-collections/vmware.vmware_rest#262]
##### SUMMARY

Unable to execute any module from vmware.vmware_rest collection. Tasks fail with FileNotFoundError.
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.5] 
  config file = /home/mkukan/code/company/ansible-vsphere/ansible.cfg
  configured module search path = ['/home/mkukan/code/company/ansible-vsphere/plugins/modules']
  ansible python module location = /home/mkukan/.pyenv/versions/3.6.14/envs/ansible-vsphere/lib/python3.6/site-packages/ansible
  ansible collection location = /home/mkukan/code/company/ansible-vsphere/collections
  executable location = /home/mkukan/.pyenv/versions/ansible-vsphere/bin/ansible
  python version = 3.6.14 (default, Aug  9 2021, 14:00:41) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/mkukan/code/company/ansible-vsphere/collections/ansible_collections
Collection         Version
------------------ -------
vmware.vmware_rest 2.1.0
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/mkukan/code/company/ansible-vsphere/ansible.cfg) = True
COLLECTIONS_PATHS(/home/mkukan/code/company/ansible-vsphere/ansible.cfg) = ['/home/mkukan/code/company/ansible-vsphere/collections']
DEFAULT_FORKS(/home/mkukan/code/company/ansible-vsphere/ansible.cfg) = 50
DEFAULT_GATHERING(/home/mkukan/code/company/ansible-vsphere/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/mkukan/code/company/ansible-vsphere/ansible.cfg) = ['/home/mkukan/code/company/ansible-vsphere/inventory.yml']
DEFAULT_MODULE_PATH(/home/mkukan/code/company/ansible-vsphere/ansible.cfg) = ['/home/mkukan/code/company/ansible-vsphere/plugins/modules']
DEFAULT_MODULE_UTILS_PATH(/home/mkukan/code/company/ansible-vsphere/ansible.cfg) = ['/home/mkukan/code/company/ansible-vsphere/plugins/module_utils']
DEFAULT_ROLES_PATH(/home/mkukan/code/company/ansible-vsphere/ansible.cfg) = ['/home/mkukan/code/company/ansible-vsphere/roles']
DEFAULT_TIMEOUT(/home/mkukan/code/company/ansible-vsphere/ansible.cfg) = 30
DEPRECATION_WARNINGS(env: ANSIBLE_DEPRECATION_WARNINGS) = False
HOST_KEY_CHECKING(/home/mkukan/code/company/ansible-vsphere/ansible.cfg) = False
INVENTORY_CACHE_ENABLED(/home/mkukan/code/company/ansible-vsphere/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/mkukan/code/company/ansible-vsphere/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/home/mkukan/code/company/ansible-vsphere/ansible.cfg) = /home/mkukan/.ansible-retry
```

##### OS / ENVIRONMENT

**vCenter 7.0.2 Build 18455184**

```
pip show aiohttp | grep Version
Version: 3.7.4.post0
#
Linux WSLHOST 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
#
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

##### STEPS TO REPRODUCE

```bash
ansible-playbook playbooks/example_access.yml -e '@vars/main.yml' -vvv
```

```yaml
---
- name: Example of VMware REST 2 Access modules
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Retrieves information about the vCenter version
      vmware.vmware_rest.appliance_system_version_info:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: false
```
```yaml
---
vcenter_hostname: vcenter-fqdn
vcenter_username: vcenter-username
vcenter_password: vcenter-password
```

##### EXPECTED RESULTS

Example
```yaml
build: '17694817'
          install_time: '2021-07-26T20:15:27.153Z'
          product: VMware vCenter Server
          releasedate: March 9, 2021
          summary: VMware vCenter Server 7.0 Update 2
          type: vCenter Server with an embedded Platform Services Controller
          version: 7.0.2.00000
```

##### ACTUAL RESULTS

```paste below
ansible-playbook [core 2.11.5] 
  config file = /home/mkukan/code/company/ansible-vsphere/ansible.cfg
  configured module search path = ['/home/mkukan/code/company/ansible-vsphere/plugins/modules']
  ansible python module location = /home/mkukan/.pyenv/versions/3.6.14/envs/ansible-vsphere/lib/python3.6/site-packages/ansible
  ansible collection location = /home/mkukan/code/company/ansible-vsphere/collections
  executable location = /home/mkukan/.pyenv/versions/ansible-vsphere/bin/ansible-playbook
  python version = 3.6.14 (default, Aug  9 2021, 14:00:41) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
Using /home/mkukan/code/company/ansible-vsphere/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/mkukan/code/company/ansible-vsphere/inventory.yml as it did not pass its verify_file() method
script declined parsing /home/mkukan/code/company/ansible-vsphere/inventory.yml as it did not pass its verify_file() method
Parsed /home/mkukan/code/company/ansible-vsphere/inventory.yml inventory source with yaml plugin
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Loading collection vmware.vmware_rest from /home/mkukan/code/company/ansible-vsphere/collections/ansible_collections/vmware/vmware_rest
Loading callback plugin default of type stdout, v2.0 from /home/mkukan/.pyenv/versions/3.6.14/envs/ansible-vsphere/lib/python3.6/site-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: example_access.yml *********************************************************************************************************************************************************************************************************************
Positional arguments: playbooks/example_access.yml
verbosity: 4
connection: smart
timeout: 30
become_method: sudo
tags: ('all',)
inventory: ('/home/mkukan/code/company/ansible-vsphere/inventory.yml',)
extra_vars: ('@/home/mkukan/code/company/ansible-vsphere/vars/main.yml',)
forks: 50
1 plays in playbooks/example_access.yml

PLAY [Example of VMware REST 2 Access modules] ***************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Retrieves information about the vCenter version] *******************************************************************************************************************************************************************************************
task path: /home/mkukan/code/company/ansible-vsphere/playbooks/example_access.yml:6
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: mkukan
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/$USER/.ansible/tmp `"&& mkdir "` echo /tmp/$USER/.ansible/tmp/ansible-tmp-1633371261.8789005-2170-111729035232488 `" && echo ansible-tmp-1633371261.8789005-2170-111729035232488="` echo /tmp/$USER/.ansible/tmp/ansible-tmp-1633371261.8789005-2170-111729035232488 `" ) && sleep 0'
Loading collection cloud.common from /home/mkukan/code/company/ansible-vsphere/collections/ansible_collections/cloud/common
Using module file /home/mkukan/code/company/ansible-vsphere/collections/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_system_version_info.py
<127.0.0.1> PUT /home/mkukan/.ansible/tmp/ansible-local-2119olihthl6/tmpr0m37iif TO /tmp/mkukan/.ansible/tmp/ansible-tmp-1633371261.8789005-2170-111729035232488/AnsiballZ_appliance_system_version_info.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /tmp/mkukan/.ansible/tmp/ansible-tmp-1633371261.8789005-2170-111729035232488/ /tmp/mkukan/.ansible/tmp/ansible-tmp-1633371261.8789005-2170-111729035232488/AnsiballZ_appliance_system_version_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/mkukan/.pyenv/versions/3.6.14/envs/ansible-vsphere/bin/python3.6 /tmp/mkukan/.ansible/tmp/ansible-tmp-1633371261.8789005-2170-111729035232488/AnsiballZ_appliance_system_version_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /tmp/mkukan/.ansible/tmp/ansible-tmp-1633371261.8789005-2170-111729035232488/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/mkukan/.ansible/tmp/ansible-tmp-1633371261.8789005-2170-111729035232488/AnsiballZ_appliance_system_version_info.py", line 100, in <module>
    _ansiballz_main()
  File "/tmp/mkukan/.ansible/tmp/ansible-tmp-1633371261.8789005-2170-111729035232488/AnsiballZ_appliance_system_version_info.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/mkukan/.ansible/tmp/ansible-tmp-1633371261.8789005-2170-111729035232488/AnsiballZ_appliance_system_version_info.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_xcwfsmol/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_system_version_info.py", line 222, in <module>
  File "/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_xcwfsmol/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_system_version_info.py", line 170, in main
  File "/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_xcwfsmol/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py", line 42, in __init__
  File "/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_xcwfsmol/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py", line 100, in run_on_daemon
  File "/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_xcwfsmol/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py", line 95, in connect
  File "/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_xcwfsmol/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py", line 27, in bind
FileNotFoundError: [Errno 2] No such file or directory
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/mkukan/.ansible/tmp/ansible-tmp-1633371261.8789005-2170-111729035232488/AnsiballZ_appliance_system_version_info.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/tmp/mkukan/.ansible/tmp/ansible-tmp-1633371261.8789005-2170-111729035232488/AnsiballZ_appliance_system_version_info.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/mkukan/.ansible/tmp/ansible-tmp-1633371261.8789005-2170-111729035232488/AnsiballZ_appliance_system_version_info.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_xcwfsmol/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_system_version_info.py\", line 222, in <module>\n  File \"/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/asyncio/base_events.py\", line 488, in run_until_complete\n    return future.result()\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_xcwfsmol/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_system_version_info.py\", line 170, in main\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_xcwfsmol/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 42, in __init__\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_xcwfsmol/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 100, in run_on_daemon\n  File \"/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/contextlib.py\", line 81, in __enter__\n    return next(self.gen)\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_xcwfsmol/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 95, in connect\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_xcwfsmol/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 27, in bind\nFileNotFoundError: [Errno 2] No such file or directory\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```

**Comment by Akasurde** [comment]
@maroskukan Thanks for reporting this issue. Could you please tell us which operating system you are using for running Ansible and the given playbook?

**Comment by maroskukan** [comment]
@Akasurde thanks for reaching out, I am running a WSL2 instance of Ubuntu 20.4.03 LTS, see output from OS / ENVIRONMENT section.

**Comment by Akasurde** [comment]
@maroskukan VMware REST modules use Ansible Turbo which internally uses Unix Socket. I think you need a Linux box for this.

cc @goneri

**Comment by maroskukan** [comment]
@Akasurde , I have setup and rerun the above scenario in Ubuntu 20.04 VM with full linux kernel
```bash
uname
Linux stackstorm 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

python --version
Python 3.8.10
```

But I am getting same results back, module failure on File not found

```json
"module_stderr": "Traceback (most recent call last):\n  File \"/tmp/vagrant/.ansible/tmp/ansible-tmp-1633516090.504055-11384-248176107363039/AnsiballZ_appliance_system_version_info.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/tmp/vagrant/.ansible/tmp/ansible-tmp-1633516090.504055-11384-248176107363039/AnsiballZ_appliance_system_version_info.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/vagrant/.ansible/tmp/ansible-tmp-1633516090.504055-11384-248176107363039/AnsiballZ_appliance_system_version_info.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.vmware.vmware_rest.plugins.modules.appliance_system_version_info', init_globals=dict(_module_fqn='ansible_collections.vmware.vmware_rest.plugins.modules.appliance_system_version_info', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_5cfwzhao/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_system_version_info.py\", line 222, in <module>\n  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n    return future.result()\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_5cfwzhao/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_system_version_info.py\", line 169, in main\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_5cfwzhao/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 42, in __init__\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_5cfwzhao/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 99, in run_on_daemon\n  File \"/usr/lib/python3.8/contextlib.py\", line 113, in __enter__\n    return next(self.gen)\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_5cfwzhao/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 95, in connect\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_5cfwzhao/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 27, in bind\nFileNotFoundError: [Errno 2] No such file or directory\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by goneri** [comment]
Hi @maroskukan. Are you sure you're got aiohttp installed?

Also, can you try this:

- open a console and load the same virtualenv
- start the following command: `PYTHONPATH=$HOME/.ansible/collections python -m ansible_collections.cloud.common.plugins.module_utils.turbo.server --socket-path $HOME/.ansible/tmp/turbo_mode.vmware.vmware_rest.socket`
- in the original console, run your playbook

You should get more information in the second console.

**Comment by maroskukan** [comment]
@goneri , Yes, aiohttp is installed. I am having issues loading those modules, likely because my paths are different,

But, what I tried is to downgrade cloud,common from 2.0.4 to 2.0.3 and the module produced the desired result.
```bash
rm -rf collections/ansible_collections/cloud
ansible-galaxy collection install cloud.common:==2.0.3

ap playbooks/example_access.yml -e '@vars/main.yml'
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Example of VMware REST 2 Access modules] **********************************************************************************

TASK [Retrieves information about the vCenter version] **************************************************************************
ok: [localhost]

PLAY RECAP **********************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by goneri** [comment]
Whoa, that's interesting. Can you try to upgrade to 2.0.4 again to validate it was not some corruption of the files that got fixed during the downgrade.

**Comment by maroskukan** [comment]
@goneri , in regards your last query. I have cloned the cloud.common into `./collections/ansible_collections/cloud/common` and moved HEAD to `b8e6abe` . Executed the playbook but received an error.

```bash
playbooks/example_access.yml -e '@vars/main.yml' -v
...
The full traceback is:
Traceback (most recent call last):
  File "/tmp/mkukan/.ansible/tmp/ansible-tmp-1633590897.5944915-8195-75313107307065/AnsiballZ_appliance_system_version_info.py", line 100, in <module>
    _ansiballz_main()
  File "/tmp/mkukan/.ansible/tmp/ansible-tmp-1633590897.5944915-8195-75313107307065/AnsiballZ_appliance_system_version_info.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/mkukan/.ansible/tmp/ansible-tmp-1633590897.5944915-8195-75313107307065/AnsiballZ_appliance_system_version_info.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_0rq_4k7z/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_system_version_info.py", line 222, in <module>
  File "/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_0rq_4k7z/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_system_version_info.py", line 170, in main
  File "/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_0rq_4k7z/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py", line 42, in __init__
  File "/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_0rq_4k7z/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py", line 100, in run_on_daemon
  File "/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_0rq_4k7z/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py", line 95, in connect
  File "/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_0rq_4k7z/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py", line 27, in bind
FileNotFoundError: [Errno 2] No such file or directory
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/mkukan/.ansible/tmp/ansible-tmp-1633590897.5944915-8195-75313107307065/AnsiballZ_appliance_system_version_info.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/tmp/mkukan/.ansible/tmp/ansible-tmp-1633590897.5944915-8195-75313107307065/AnsiballZ_appliance_system_version_info.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/mkukan/.ansible/tmp/ansible-tmp-1633590897.5944915-8195-75313107307065/AnsiballZ_appliance_system_version_info.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_0rq_4k7z/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_system_version_info.py\", line 222, in <module>\n  File \"/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/asyncio/base_events.py\", line 488, in run_until_complete\n    return future.result()\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_0rq_4k7z/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_system_version_info.py\", line 170, in main\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_0rq_4k7z/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 42, in __init__\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_0rq_4k7z/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 100, in run_on_daemon\n  File \"/home/mkukan/.pyenv/versions/3.6.14/lib/python3.6/contextlib.py\", line 81, in __enter__\n    return next(self.gen)\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_0rq_4k7z/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 95, in connect\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_system_version_info_payload_0rq_4k7z/ansible_vmware.vmware_rest.appliance_system_version_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 27, in bind\nFileNotFoundError: [Errno 2] No such file or directory\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by Akasurde** [comment]
I am using Ubuntu 20.04.

For me, 

Default Collection location - Works

```
ansible [core 2.11.5]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.2
  libyaml = True
```

Custom collection location - Works

```
ansible [core 2.11.5]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/vagrant/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.2
  libyaml = True
```

**Comment by maroskukan** [comment]
@goneri , yes, that "stackstorm" VM was build using Vagrant. It configuration file is simple, I am not using any folder mapping between hosts and guest. 

```ruby
# -*- mode: ruby -*-                                            
# vi: set ft=ruby :                                             
                                                                
Vagrant.configure("2") do |config|                              
  config.vm.provider "hyperv" do |h|                            
    h.enable_virtualization_extensions = true                   
    h.linked_clone = true                                       
    h.memory = 4096                                             
    h.maxmemory = 4096                                          
  end                                                           
                                                                
  config.vm.box = "generic/ubuntu2004"                          
  config.vm.network "public_network", bridge: "Default Switch"  
                                                                
  config.vm.define "stackstorm" do |stackstorm|                 
    stackstorm.vm.hostname = "stackstorm"                       
  end                                                           
end                                                             
```

The [vanilla Ubuntu VM](https://github.com/ansible-collections/vmware.vmware_rest/issues/262#issuecomment-937540032) which I referenced in that last example, was build from official cloud image and the minimal tools to run these modules. If have some time and will, try that scenario locally - installing modules in custom directory. With following project `ansible.cfg` configuration file
```ini
[defaults]                                        
become_user           = 'root'                    
forks                 = 50                        
# vault_password_file   = ~/.ansible_vault_pass   
retry_files_enabled   = False                     
gathering             = smart                     
retry_files_save_path = ~/.ansible-retry          
remote_tmp            = /tmp/$USER/.ansible/tmp   
inventory             = ./inventory.yml           
timeout               = 30                        
host_key_checking     = False                     
nocows                = True                      
roles_path            = ./roles                   
library               = ./plugins/modules         
module_utils          = ./plugins/module_utils    
collections_paths     = ./collections             
                                                  
[inventory]                                       
cache = no                                        
                                                  
#[privilege_escalation]                           
#become_ask_pass       = True                     
```

Since we do not see a lot of issues reported around this It might happen that it only occurs in certain corner case situations. In that case I would not like to waste time and wait until more users would have the same issue.

**Comment by tadeboro** [comment]
My guess would be that you are having problems because you are using `$USER` in your `remote_tmp` configuration option. Ansible does expand variables in the `remote_tmp` value (https://github.com/ansible/ansible/blob/a4a7a348936b9d2ea346ef465c1958c459ec83ee/lib/ansible/module_utils/basic.py#L551), which is why other modules are working fine. Turbo modules skip the variable expansion and that results in the error you see here.

I am pretty sure that the error will go away if you replace lines https://github.com/ansible-collections/cloud.common/blob/a6fece122fd684e31dc29515ff8d823973620d96/plugins/module_utils/turbo/module.py#L120-L122 with this:

```python
        from os.path import expanduser, expandvars

        abs_remote_tmp = expanduser(expandvars(self._remote_tmp))
```

**Comment by maroskukan** [comment]
@tadeboro well done, this change indeed, makes a difference in the presented use case. I think once your MR will be closed we can close this issue as well.
