### ISSUE TITLE
vCenter NTP conflict with multiple vCenter in Inventory with cloud.common > 2.0.3

### ISSUE THREAD

**Issue by MallocArray** [ansible-collections/vmware.vmware_rest#336]
##### SUMMARY

When running a playbook to configure multiple vCenters, using the NTP modules vmware.vmware_rest.appliance_ntp and vmware.vmware_rest.appliance_timesync, along with other tasks, the playbook works fine with the cloud.common module running 2.0.3 or less, but any version higher will sometimes error out, but only if running the playbook with multiple vCenters in Inventory.  If running against a single vCenter, it works as expected.  I suspect a conflict due to concurrent operations that only impact later versions of cloud.common.  

I am running against and inventory with 11 vCenters in it.  Multiple SSO domains, although some are in linked mode.
It may happen less frequently if I only run the NTP related tasks instead of the full playbook, but sometimes am able to get it to fail even when just running 2 NTP tasks

Temporary workaround was to limit cloud.common to no higher than 2.0.3 but several things are requiring newer versions.  Another potential workaround would be to split the NTP tasks to a separate play and change that play to `serial: 1` to prevent multiple operations at the same time

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware.vmware_rest.appliance_ntp and vmware.vmware_rest.appliance_timesync
Also collection cloud.common > 2.0.3

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.6]
  config file = /runner/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

also occurred with ansible 2.10.17
```

##### COLLECTION VERSION

```paste below
Collection   Version
------------ -------
cloud.common 2.1.1 
vmware.vmware_rest 2.1.5  

Note: also occurs with vmware.vmware_rest 2.1.4 and cloud.common greater than 2.0.3
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/runner/ansible.cfg) = ['/runner/collections']
DEFAULT_FILTER_PLUGIN_PATH(/runner/ansible.cfg) = ['/runner/custom_filters']
DEFAULT_ROLES_PATH(/runner/ansible.cfg) = ['/runner/roles']
DEFAULT_STRATEGY_PLUGIN_PATH(/runner/ansible.cfg) = ['/runner/custom_plugins/mitogen-0.3.0-rc.0/ansible_mitogen/plugins/strategy']
DEFAULT_TIMEOUT(/runner/ansible.cfg) = 40
HOST_KEY_CHECKING(/runner/ansible.cfg) = False
PARAMIKO_LOOK_FOR_KEYS(/runner/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ansible Execution Environment based on 
quay.io/ansible/ansible-runner:stable-2.12-latest

vCenters running 7.0.3.00300

##### STEPS TO REPRODUCE

```yaml
- name: vCenter Appliance Configuration

  hosts: vCenters
  gather_facts: false
  vars_files:
    - vars/ssh_settings.yml

  tasks:
    - name: Adjust the NTP configuration
      # https://github.com/ansible-collections/vmware.vmware_rest/blob/main/docs/vmware.vmware_rest.appliance_ntp_module.rst
      vmware.vmware_rest.appliance_ntp:
        vcenter_hostname: "{{ inventory_hostname }}"
        vcenter_username: "{{ vcenter_user }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: "{{ vmware_validate_certs }}"
        servers: "{{ ntp_servers }}"
      delegate_to: localhost
      tags:
        - ntp
      notify: Restart the ntpd service


    - name: Enable NTP timesync
      # https://github.com/ansible-collections/vmware.vmware_rest/blob/main/docs/vmware.vmware_rest.appliance_timesync_module.rst
      vmware.vmware_rest.appliance_timesync:
        vcenter_hostname: "{{ inventory_hostname }}"
        vcenter_username: "{{ vcenter_user }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: "{{ vmware_validate_certs }}"
        mode: NTP
      delegate_to: localhost
      tags:
        - ntp
```

##### EXPECTED RESULTS

OK status from all vCenters

##### ACTUAL RESULTS

```paste below
Read vars_file 'vars/ssh_settings.yml'
Read vars_file 'vars/ssh_settings.yml'
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1654896013.623815-4429-236742041218958 `" && echo ansible-tmp-1654896013.623815-4429-236742041218958="` echo /root/.ansible/tmp/ansible-tmp-1654896013.623815-4429-236742041218958 `" ) && sleep 0'
Using module file /runner/collections/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_ntp.py
<localhost> PUT /home/runner/.ansible/tmp/ansible-local-4097xy3jvrnd/tmp3vk5xthg TO /root/.ansible/tmp/ansible-tmp-1654896013.623815-4429-236742041218958/AnsiballZ_appliance_ntp.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1654896013.623815-4429-236742041218958/ /root/.ansible/tmp/ansible-tmp-1654896013.623815-4429-236742041218958/AnsiballZ_appliance_ntp.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1654896013.623815-4429-236742041218958/AnsiballZ_appliance_ntp.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1654895984.1472194-4310-234706672751997/ > /dev/null 2>&1 && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1654895992.1502159-4359-49216321348415/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_4c_lt476/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py", line 106, in communicate
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1654895992.1502159-4359-49216321348415/AnsiballZ_appliance_ntp.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1654895992.1502159-4359-49216321348415/AnsiballZ_appliance_ntp.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1654895992.1502159-4359-49216321348415/AnsiballZ_appliance_ntp.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.vmware.vmware_rest.plugins.modules.appliance_ntp', init_globals=dict(_module_fqn='ansible_collections.vmware.vmware_rest.plugins.modules.appliance_ntp', _modlib_path=modlib_path),
  File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_4c_lt476/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_ntp.py", line 310, in <module>
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_4c_lt476/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_ntp.py", line 201, in main
  File "/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_4c_lt476/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py", line 119, in __init__
  File "/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_4c_lt476/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py", line 154, in run_on_daemon
  File "/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_4c_lt476/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py", line 109, in communicate
ansible_collections.cloud.common.plugins.module_utils.turbo.exceptions.EmbeddedModuleUnexpectedFailure: Cannot decode plugin answer: b''
fatal: [vcenter4.domain.com -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_4c_lt476/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 106, in communicate\n  File \"/usr/lib64/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1654895992.1502159-4359-49216321348415/AnsiballZ_appliance_ntp.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1654895992.1502159-4359-49216321348415/AnsiballZ_appliance_ntp.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1654895992.1502159-4359-49216321348415/AnsiballZ_appliance_ntp.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.vmware.vmware_rest.plugins.modules.appliance_ntp', init_globals=dict(_module_fqn='ansible_collections.vmware.vmware_rest.plugins.modules.appliance_ntp', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_4c_lt476/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_ntp.py\", line 310, in <module>\n  File \"/usr/lib64/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n    return future.result()\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_4c_lt476/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_ntp.py\", line 201, in main\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_4c_lt476/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 119, in __init__\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_4c_lt476/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 154, in run_on_daemon\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_4c_lt476/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 109, in communicate\nansible_collections.cloud.common.plugins.module_utils.turbo.exceptions.EmbeddedModuleUnexpectedFailure: Cannot decode plugin answer: b''\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_o7a5pswp/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py", line 106, in communicate
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1654895984.1472194-4310-234706672751997/AnsiballZ_appliance_ntp.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1654895984.1472194-4310-234706672751997/AnsiballZ_appliance_ntp.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1654895984.1472194-4310-234706672751997/AnsiballZ_appliance_ntp.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.vmware.vmware_rest.plugins.modules.appliance_ntp', init_globals=dict(_module_fqn='ansible_collections.vmware.vmware_rest.plugins.modules.appliance_ntp', _modlib_path=modlib_path),
  File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_o7a5pswp/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_ntp.py", line 310, in <module>
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_o7a5pswp/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_ntp.py", line 201, in main
  File "/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_o7a5pswp/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py", line 119, in __init__
  File "/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_o7a5pswp/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py", line 154, in run_on_daemon
  File "/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_o7a5pswp/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py", line 109, in communicate
ansible_collections.cloud.common.plugins.module_utils.turbo.exceptions.EmbeddedModuleUnexpectedFailure: Cannot decode plugin answer: b''
fatal: [wdc-vravc01.mercyhost.local -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_o7a5pswp/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 106, in communicate\n  File \"/usr/lib64/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1654895984.1472194-4310-234706672751997/AnsiballZ_appliance_ntp.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1654895984.1472194-4310-234706672751997/AnsiballZ_appliance_ntp.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1654895984.1472194-4310-234706672751997/AnsiballZ_appliance_ntp.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.vmware.vmware_rest.plugins.modules.appliance_ntp', init_globals=dict(_module_fqn='ansible_collections.vmware.vmware_rest.plugins.modules.appliance_ntp', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_o7a5pswp/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_ntp.py\", line 310, in <module>\n  File \"/usr/lib64/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n    return future.result()\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_o7a5pswp/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_ntp.py\", line 201, in main\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_o7a5pswp/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 119, in __init__\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_o7a5pswp/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 154, in run_on_daemon\n  File \"/tmp/ansible_vmware.vmware_rest.appliance_ntp_payload_o7a5pswp/ansible_vmware.vmware_rest.appliance_ntp_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 109, in communicate\nansible_collections.cloud.common.plugins.module_utils.turbo.exceptions.EmbeddedModuleUnexpectedFailure: Cannot decode plugin answer: b''\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1654896014.4968283-4448-256359162398105 `" && echo ansible-tmp-1654896014.4968283-4448-256359162398105="` echo /root/.ansible/tmp/ansible-tmp-1654896014.4968283-4448-256359162398105 `" ) && sleep 0'
Using module file /runner/collections/ansible_collections/vmware/vmware_rest/plugins/modules/appliance_ntp.py
<localhost> PUT /home/runner/.ansible/tmp/ansible-local-4097xy3jvrnd/tmpwbakydo9 TO /root/.ansible/tmp/ansible-tmp-1654896014.4968283-4448-256359162398105/AnsiballZ_appliance_ntp.py
```

**Comment by MallocArray** [comment]
Looks like the appliance_networking_proxy module is also impacted

**Comment by goneri** [comment]
Thank you for the report.
