### ISSUE TITLE
Unable to use any lookup with latest collection and Ansible on RHEL9

### ISSUE THREAD

**Issue by milesbarry** [ansible-collections/vmware.vmware_rest#421]
##### SUMMARY
Unable to use any lookups without getting an exception

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
datacenter_moid

##### ANSIBLE VERSION
```
ansible [core 2.15.1]
  config file = /home/diablo/.ansible.cfg
  configured module search path = ['/home/diablo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/diablo/ansible/venv/ansible-latest/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/diablo/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/diablo/ansible/venv/ansible-latest/bin/ansible
  python version = 3.9.16 (main, May 29 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/home/diablo/ansible/venv/ansible-latest/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### OS / ENVIRONMENT
RHEL9 with python 3.9 virtual environment running latest Ansible

Hi, every time I attempt to use the lookups I get an exception.

```
Tuesday 27 June 2023  16:52:08 +0100 (0:00:00.018)       0:00:00.034 **********
Loading collection cloud.common from /home/diablo/ansible/venv/ansible-latest/lib64/python3.9/site-packages/ansible_collections/cloud/common
exception during Jinja2 execution: Traceback (most recent call last):
  File "/home/diablo/ansible/venv/ansible-latest/lib64/python3.9/site-packages/ansible/template/__init__.py", line 831, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
  File "/home/diablo/ansible/venv/ansible-latest/lib64/python3.9/site-packages/ansible_collections/cloud/common/plugins/plugin_utils/turbo/lookup.py", line 57, in run_on_daemon
    return self.execute(terms=terms, variables=variables, **kwargs)
  File "/home/diablo/ansible/venv/ansible-latest/lib64/python3.9/site-packages/ansible_collections/cloud/common/plugins/plugin_utils/turbo/lookup.py", line 89, in execute
    raise EmbeddedModuleUnexpectedFailure(errors)
ansible_collections.cloud.common.plugins.module_utils.turbo.exceptions.EmbeddedModuleUnexpectedFailure: No _run() found
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'vmware.vmware_rest.datacenter_moid'. Error was a <class 'ansible_collections.cloud.common.plugins.module_utils.turbo.exceptions.EmbeddedModuleUnexpectedFailure'>, original message: No _run() found. No _run() found"
}
```

Does anyone know what is wrong here please?

Best wishes.

**Comment by azrdev** [comment]
I see the same error on EE-supported-RHEL8:
~~~
An unhandled exception occurred while running the lookup plugin 'vmware.vmware_rest.folder_moid'. Error was a <class 'ansible_collections.cloud.common.plugins.module_utils.turbo.exceptions.EmbeddedModuleUnexpectedFailure'>, original message: No _run() found. No _run() found
~~~

This is on Ansible Automation Controller 4.4.6, and was introduced between the EEs:

- ee-supported-rhel8 @ 2023-05-15 ee-supported-rhel8@sha256:dc9c26ee51613e7da8d74038e44e87133715076d8e67f9be2a17124cad2a4633

- ee-supported-rhel8 @ 2023-07-20 ee-supported-rhel8@sha256:0c89d8fed5b0dea48ce5e15069678169b983765c6dfb0ee431c07874a3c31a0a

**Comment by azrdev** [comment]
seems to be the same issue as #356

**Comment by gravesm** [comment]
@milesbarry @azrdev Could you try using the latest version of cloud.common? This problem should have been fixed in https://github.com/ansible-collections/cloud.common/pull/130

**Comment by mariolenz** [comment]
> @milesbarry @azrdev Could you try using the latest version of cloud.common? This problem should have been fixed in [ansible-collections/cloud.common#130](https://github.com/ansible-collections/cloud.common/pull/130)

Looks like this would be `cloud.common` 2.1.4.

**Comment by azrdev** [comment]
Seems to be fixed with cloud.common 2.1.4 -- thanks!
